/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package obb.aps;

import java.awt.Font;

/**
 *
 * @author Eduardo
 */
public class OBB extends javax.swing.JFrame {

    private int tamanhofont = 18;
    private int aux=0;

    /**
     * Creates new form OBB
     */
    public OBB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        areatexto = new javax.swing.JTextArea();
        fontdown = new javax.swing.JButton();
        fontup = new javax.swing.JButton();
        jSerif = new javax.swing.JButton();
        jSansSerif = new javax.swing.JButton();
        jMonospaced = new javax.swing.JButton();
        jNegrito = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        areatexto.setColumns(20);
        areatexto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        areatexto.setRows(5);
        jScrollPane1.setViewportView(areatexto);

        fontdown.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        fontdown.setText("Font -");
        fontdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fontdownActionPerformed(evt);
            }
        });

        fontup.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        fontup.setText("Font +");
        fontup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fontupActionPerformed(evt);
            }
        });

        jSerif.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jSerif.setText("Serif");
        jSerif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSerifActionPerformed(evt);
            }
        });

        jSansSerif.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jSansSerif.setText("SansSerif");
        jSansSerif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSansSerifActionPerformed(evt);
            }
        });

        jMonospaced.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N
        jMonospaced.setText("Monospaced");
        jMonospaced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMonospacedActionPerformed(evt);
            }
        });

        jNegrito.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jNegrito.setText("Negrito");
        jNegrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNegritoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSerif)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSansSerif)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMonospaced, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fontdown)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(fontup))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jNegrito)
                .addGap(40, 40, 40))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fontdown)
                        .addComponent(fontup))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSansSerif, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSerif)
                        .addComponent(jMonospaced, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNegrito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fontupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fontupActionPerformed
        // TODO add your handling code here:
        
        tamanhofont++;
        areatexto.setFont(new Font("Defaut",Font.PLAIN,tamanhofont));
    }//GEN-LAST:event_fontupActionPerformed

    private void jNegritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNegritoActionPerformed
        if(aux==0){
        areatexto.setFont(new Font("Defaut",Font.BOLD,tamanhofont));
        aux=1;
        }
        else{areatexto.setFont(new Font("Defaut",Font.PLAIN,tamanhofont));
        aux=0;}
    }//GEN-LAST:event_jNegritoActionPerformed

    private void jSerifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSerifActionPerformed
        // TODO add your handling code here:
        
        areatexto.setFont(new Font("Serif",Font.PLAIN,tamanhofont));
        
    }//GEN-LAST:event_jSerifActionPerformed

    private void fontdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fontdownActionPerformed
        // TODO add your handling code here:
         tamanhofont--;
        areatexto.setFont(new Font("Defaut",Font.PLAIN,tamanhofont));
    }//GEN-LAST:event_fontdownActionPerformed

    private void jSansSerifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSansSerifActionPerformed
        // TODO add your handling code here:
        areatexto.setFont(new Font("SansSerif",Font.PLAIN,tamanhofont));
    }//GEN-LAST:event_jSansSerifActionPerformed

    private void jMonospacedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMonospacedActionPerformed
        // TODO add your handling code here:
         areatexto.setFont(new Font("Monospaced",Font.PLAIN,tamanhofont));
    }//GEN-LAST:event_jMonospacedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OBB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OBB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OBB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OBB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OBB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areatexto;
    private javax.swing.JButton fontdown;
    private javax.swing.JButton fontup;
    private javax.swing.JButton jMonospaced;
    private javax.swing.JButton jNegrito;
    private javax.swing.JButton jSansSerif;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSerif;
    // End of variables declaration//GEN-END:variables
}
